apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  labels:
    microservice: products-service
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: products-service
  template:
    metadata:
      labels:
        microservice: products-service
    spec:
      containers:
      - name: products-service
        image: bte1lar/products-service:0.1.4
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "200m"
            memory: "200Mi"
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: products-service
              key: PORT
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: products-service
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: products-service
              key: POSTGRES_PORT
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: products-service
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: products-service
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              name: products-service
              key: POSTGRES_DATABASE
