apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    microservice: products-service
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    microservice: products-service
