# https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
apiVersion: v1
kind: Secret
metadata:
  name: github-actions-runner
  annotations:
    kubernetes.io/service-account.name: github-actions-runner
type: kubernetes.io/service-account-token
