apiVersion: v1
clusters:
- cluster:
    server: $KUBERNETES_CLUSTER_API_BASE_URL
  name: wlosiara-pl
contexts:
- context:
    cluster: wlosiara-pl
    namespace: default
    user: github-actions-runner
  name: wlosiara-pl-github-actions-runner
current-context: wlosiara-pl-github-actions-runner
kind: Config
preferences: {}
users:
- name: github-actions-runner
  user:
    token: $GITHUB_ACTIONS_RUNNER_TOKEN
