apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: chartmuseum
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: chartmuseum.dev.wlosiara.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-chartmuseum"
                port:
                  number: 8080
