apiVersion: v1
kind: Service
metadata:
    name: wlosiara-client-server
    labels:
        microservice: wlosiara-client-server
spec:
    type: ClusterIP
    sessionAffinity: ClientIP
    ports:
        - port: 80
          targetPort: 3000
          protocol: TCP
    selector:
        microservice: wlosiara-client-server
