name: Setup image pull secrets

on:
  workflow_dispatch:

jobs:
  setup_image_pull_secrets:
    runs-on: ubuntu-latest
    name: Setup image pull secrets
    steps:
      - name: Setup .kube/config
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
      # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line
      - name: Create image pull secret
        run: |
          kubectl apply secret docker-registry docker-registry --docker-server=${{ secrets.DOCKER_REGISTRY_HOST }} --docker-username=${{ secrets.DOCKER_REGISTRY_USERNAME }} --docker-password=${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      # https://stackoverflow.com/questions/55223075/automatically-use-secret-when-pulling-from-private-registry
      - name: Configure default service account to use image pull secret
        run: |
          kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "docker-registry"}]}'
