apiVersion: v1
kind: Service
metadata:
  name: products-database-external
  labels:
    microservice: products-database
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30001
  selector:
    microservice: products-database
